[
  "You don't often get email from krystof.penka@outlook.com. Learn why this is",
  "important [https://aka.ms/LearnAboutSenderIdentification]",
  "Process Notification",
  "Process:",
  "AHCZ Hlavní Proces_448343, BKP-A-X/0/4, Blok kompl, 1.2 (Design)$AHCZ Založení", //4
  "série K",
  "Process description:",
  "Activity name:",
  "Email: Informace do výroby",
  "Activity description:",
  "Email: Informace do výroby / Info an PR",
  "Pokud vyráběný: Informace do výroby / Bei Eigenfertigung: Info an PR",
  "Subject object:",
  "448343, BKP-A-X/0/4, Blok kompl, 1.2 (Design)",
  "--------------------------------------------------------------------------------",
  "Product Name:",
  "AH-CZ-SECURE",
  "Product Creator:",
  "Administrator Organisation [windchill@argo-hytos.com]",
  "Host Organization:",
  "ARGO-HYTOS",
  "Product Description:",
  "None",
  "--------------------------------------------------------------------------------",
  "SAP pohledy založeny pro výrobu."
]